
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Markuss
 */
public class Paparde extends javax.swing.JFrame {
    int punktusk;
    double[][] punkti = new double[1][2];
    double[][] reiz1 = { {0.00, 0.00} , {0.00, 0.16} };
    double[][] reiz2 = { {0.85, -0.04} , {0.04, 0.85} };
    double[][] reiz3 = { {0.20, 0.23} , {-0.26, 0.22} };
    double[][] reiz4 = { {-0.15, 0.26} , {0.28, 0.24} };
    double[] p2 = {0.00, 1.60};
    double[] p3 = {0.00, 1.60};   
    double[] p4 = {0.00, 0.44};
    

    /**
     * Creates new form Paparde
     */
    public Paparde() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        punkti_text = new javax.swing.JTextField();
        poga = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(874, 684));

        punkti_text.setText("80000");
        punkti_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punkti_textActionPerformed(evt);
            }
        });

        poga.setFont(new java.awt.Font("GT Eesti Pro Display Medium", 0, 14)); // NOI18N
        poga.setForeground(new java.awt.Color(0, 0, 255));
        poga.setText("zīmēt");
        poga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pogaMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("GT Eesti Pro Display Medium", 0, 18)); // NOI18N
        jLabel1.setText("Cik punktus zīmēsim?");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 935, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)
                        .addComponent(punkti_text, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(poga, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(punkti_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void punkti_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punkti_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punkti_textActionPerformed

    private void pogaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pogaMouseClicked

        punktusk = Integer.parseInt(punkti_text.getText());
        zimesana(punktusk);
    }//GEN-LAST:event_pogaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paparde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paparde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paparde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paparde.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paparde().setVisible(true);
            }
        });
    }
    
    
    public void reizina(double[][] r){
        double[][] c = new double[1][2];
        
        for(int i=0; i<1; i++){
           for(int j=0 ; j<2; j++){
               c[i][j]=0;
               for (int t=0; t<2; t++){
                   c[i][j] += punkti[i][t]* r[t][j];
               }
            }
        }
        
        for (int m=0; m<1; m++){
            for(int g=0; g<2; g++){
                punkti[m][g] = c[m][g];
            } 
        }
    }
    
    public void pieskaita(double[] p){
        double[][] c = new double[1][2];
        for(int i=0;i<1;i++){ 
            for(int t=0;t<2;t++){  
                c[i][t] = punkti[i][t] + p[t];
                punkti[i][t] = c[i][t];
            }
        }      
    }
    
    public void zimesana (int punktusk){
        Graphics g = Panel.getGraphics();
        Color myGreen = new Color(82, 141, 67);
        g.setColor (myGreen);
        
        int augst = Panel.getHeight();
        int plat = Panel.getWidth();

        
        Random rand = new Random();
        
        for (int i=0; i<punktusk; i++){
            g.drawRect((int)(punkti[0][0] / 12 * plat + 400),(int)(punkti[0][1] / 15 * augst + 50), 1, 1);

            double p = Math.random();
            if (p <= 0.01){
                reizina(reiz1);
            }else if (0.01 < p && p <= 0.86) {
                reizina(reiz2);
                pieskaita(p2);
            }else if (0.086 < p && p <= 0.93){
                reizina(reiz3);
                pieskaita(p3);
            }else if (0.93 < p && p <= 1) {
                reizina(reiz4);
                pieskaita(p4);
            }
            
        }        
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton poga;
    private javax.swing.JTextField punkti_text;
    // End of variables declaration//GEN-END:variables
}
