
import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Markuss
 */
public class Serpinskis extends javax.swing.JFrame {
    int punktusk;
    double[][] punkti = new double[1][2];
    double[][] reiz = { {0.5, 0.0} , {0.0, 0.5} };
    double[] p1 = {0.0, 150.0};
    double[] p2 = {150.0, 0.0};            

    /**
     * Creates new form Serpinskis
     */
    public Serpinskis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        punkti_text = new javax.swing.JTextField();
        poga = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("GT Eesti Pro Display Medium", 0, 18)); // NOI18N
        jLabel1.setText("Cik punktus zīmēsim?");

        punkti_text.setText("10000");
        punkti_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punkti_textActionPerformed(evt);
            }
        });

        poga.setFont(new java.awt.Font("GT Eesti Pro Display Medium", 0, 14)); // NOI18N
        poga.setForeground(new java.awt.Color(0, 0, 255));
        poga.setText("zīmēt");
        poga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pogaMouseClicked(evt);
            }
        });

        Panel.setPreferredSize(new java.awt.Dimension(480, 480));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(punkti_text, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addComponent(poga, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(punkti_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void punkti_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punkti_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punkti_textActionPerformed

    private void pogaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pogaMouseClicked

        punktusk = Integer.parseInt(punkti_text.getText());
        zimesana(punktusk);
    }//GEN-LAST:event_pogaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Serpinskis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Serpinskis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Serpinskis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Serpinskis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Serpinskis().setVisible(true);
            }
        });
    }
    
    public void reizina(double[][] r){
        double[][] c = new double[1][2];
        for(int i=0; i<1; i++){
           for(int j=0 ; j<2; j++){
               c[i][j]=0;
               for (int t=0; t<2; t++){
                   c[i][j] += punkti[i][t]* r[t][j];
               }
            }
        }
//        System.out.println(c[0][0] + "test" + c[0][1]);
        for (int m=0; m<1; m++){
            for(int g=0; g<2; g++){
                punkti[m][g] = c[m][g];
//                System.out.println(punkti[m][g] + "test");
            } 
        }
    }
    
    public void pieskaita(double[] p){
        double[][] c = new double[1][2];
        for(int i=0;i<1;i++){ 
            for(int t=0;t<2;t++){  
                c[i][t] = punkti[i][t] + p[t];
                punkti[i][t] = c[i][t];
            }
        }
    }
    
    public void zimesana (int punktusk){
        Graphics g = this.getGraphics();   
        g.setColor (Color.DARK_GRAY);
        Random rand = new Random();
        
        for (int i=0; i<punktusk; i++){
            g.drawRect((int)punkti[0][0] + 200,(int)punkti[0][1] + 200, 1, 1);
            int p = rand.nextInt(3);
//            System.out.println(p + "test2");
            if (p==0){
                reizina(reiz);
            }else {
                if (p==1) {
                reizina(reiz);
                pieskaita(p1);
                } else {
                    reizina (reiz);
                    pieskaita(p2);
                }
            }
        }
               
     }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton poga;
    private javax.swing.JTextField punkti_text;
    // End of variables declaration//GEN-END:variables
}
